### ISSUE TITLE
Cursor size doubled in systray

### ISSUE THREAD

**Issue by DhruvaSambrani** [vetu104/dwlb#5]

**Comment by vetu104** [comment]
Seems like it's related to GTK4 updates. GNOME47 just got released so there have been some changes.

https://gitlab.gnome.org/GNOME/gtk/-/issues/7042
https://gitlab.gnome.org/GNOME/gtk/-/issues/7043

Is there an issue with other GTK4 applications or is it just the systray?

**Comment by DhruvaSambrani** [comment]
Yes you are right. I don't use any other gtk4 apps it seems, so did not realise this.
